birdie-game/aviary/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('update-goals/', views.update_end_of_round_goals, name='update_end_of_round_goals'),
    path('edit_cube_count/', views.edit_cube_count, name='edit_cube_count'),
    path('edit_nectar_count/', views.edit_nectar_count, name='edit_nectar_count'),
    path('board/<int:pk>/', views.board, name='board'),
    path('<str:bird_name>/', views.detail, name='detail'),
    path('board/<int:board_id>/update/<pk>/', views.BirdUpdateView.as_view(), name='birdcard_update'),
    path('board/<pk>/add/', views.update_board, name='update_board'),
    path('board/create/', views.create_board, name='create_board'),
    path('board/<pk>/goals/', views.end_of_round_goals, name='end_of_round_goals'),
    path('board/<pk>/bonus-cards/view/', views.bonus_cards, name='bonus_cards'),
    path('board/<pk>/bonus-cards/add/', views.add_bonus_card, name='add_bonus_card'),
    path('board/<board_pk>/bonus-cards/<card_pk>/delete/', views.delete_bonus_card, name='delete_bonus_card'),
    path('board/bonus-cards/update', views.update_bonus_card, name='update_bonus_card'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

birdie-game/birdie-game/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aviary/', include('aviary.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

birdie-game/aviary/models.py
from django import forms
from django.db import models
from django.core.validators import MaxValueValidator
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _

# Create your models here.

class Habitat(models.Model):
    id = models.AutoField(primary_key=True)
    habitat_name = models.CharField(max_length=9, default="forest")

    def __str__(self):
        return self.habitat_name
    
class Food(models.Model):
    id = models.AutoField(primary_key=True)
    food_name = models.CharField(max_length=6, default="default")

    def __str__(self):
        return self.food_name

class FoodJunction(models.Model):
    card = models.ForeignKey("BirdCard", on_delete=models.CASCADE)
    food = models.ManyToManyField(Food)

    def __str__(self):
        food_str = ""
        for f in self.food.all():
            food_str = food_str + f.food_name + " or "
        food_str = food_str[:-4]
        return self.card.name + " eats " + food_str
    
    class Meta:
        ordering = ['card__name']

class BirdCardTemplate(models.Model):
    """
    This is a template model for BirdCard.
    It is used to create the BirdCard model with the necessary fields.
    """
    # nest types
    NEST_TYPES = (
        ('g', 'Ground'),
        ('c', 'Cavity'),
        ('b', 'Bowl'),
        ('s', 'Stick'),
        ('n', 'None'),
        ('a', 'Star'),
    )

    # ability types
    ABILITY_TYPES = (
        ('w', 'White'),
        ('b', 'Brown'),
        ('t', 'Teal'),
        ('y', 'Yellow'),
        ('p', 'Pink'),
    )

    # direction facing
    FACING_DIRECTION = (
        ('r', 'Right'),
        ('l', 'Left'),
        ('f', 'Forward'),
    )
    
    name = models.CharField(max_length=50, default="Bird")
    nest_size = models.PositiveIntegerField(default=1, validators=[MaxValueValidator(6)])
    nest_type = models.CharField(max_length=1, choices=NEST_TYPES, default='n')
    wingspan = models.PositiveIntegerField(default=1)
    feathers = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(9)])
    ability_desc = models.CharField(max_length=200, default="No ability")
    ability_type = models.CharField(max_length=1, choices=ABILITY_TYPES, default='w')
    direction_facing = models.CharField(max_length=1, choices=FACING_DIRECTION, default='f')
    habitats = models.ManyToManyField(Habitat)
    first_food = models.ForeignKey("Food", related_name="birdcard_template_first_food", default=None, on_delete=models.SET_NULL, null=True)
    second_food = models.ForeignKey("Food", related_name="birdcard_template_second_food", default=None, on_delete=models.SET_NULL, null=True)
    third_food = models.ForeignKey("Food", related_name="birdcard_template_third_food", default=None, on_delete=models.SET_NULL, null=True)
    costs_one_food = models.BooleanField(default=False, help_text="Does this bird cost one food to play?")

    def __str__(self):
        return self.name
    
# each field name should be the same as a field the BirdCard model
class BoardUpdateForm(forms.Form):
    forest_1 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Forest Bird 1")
    forest_2 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Forest Bird 2")
    forest_3 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Forest Bird 3")
    forest_4 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Forest Bird 4")
    forest_5 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Forest Bird 5")

    grassland_1 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Grassland Bird 1")
    grassland_2 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Grassland Bird 2")
    grassland_3 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Grassland Bird 3")
    grassland_4 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Grassland Bird 4")
    grassland_5 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Grassland Bird 5")

    wetland_1 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Wetland Bird 1")
    wetland_2 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Wetland Bird 2")
    wetland_3 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Wetland Bird 3")
    wetland_4 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Wetland Bird 4")
    wetland_5 = forms.ModelChoiceField(queryset=BirdCardTemplate.objects.all(), required=False, label="Wetland Bird 5")

class BirdCard(models.Model):
    # nest types
    NEST_TYPES = (
        ('g', 'Ground'),
        ('c', 'Cavity'),
        ('b', 'Bowl'),
        ('s', 'Stick'),
        ('n', 'None'),
        ('a', 'Star'),
    )

    # ability types
    ABILITY_TYPES = (
        ('w', 'White'),
        ('b', 'Brown'),
        ('t', 'Teal'),
        ('y', 'Yellow'),
        ('p', 'Pink'),
    )

    # direction facing
    FACING_DIRECTION = (
        ('r', 'Right'),
        ('l', 'Left'),
        ('f', 'Forward'),
    )

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    nest_size = models.PositiveIntegerField(default=1, validators=[MaxValueValidator(6)])
    nest_type = models.CharField(max_length=1, choices=NEST_TYPES, default='n')
    wingspan = models.PositiveIntegerField(default=1)
    habitats = models.ManyToManyField(Habitat)
    feathers = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(9)])
    ability_desc = models.CharField(max_length=200)
    ability_type = models.CharField(max_length=1, choices=ABILITY_TYPES, default='w')
    direction_facing = models.CharField(max_length=1, choices=FACING_DIRECTION, default='f')
    first_food = models.ForeignKey("Food", related_name="birdcard_first_food", on_delete=models.SET_NULL, default=None, null=True)
    second_food = models.ForeignKey("Food", related_name="birdcard_second_food", on_delete=models.SET_NULL, default=None, null=True)
    third_food = models.ForeignKey("Food", related_name="birdcard_third_food", on_delete=models.SET_NULL, default=None, null=True)
    costs_one_food = models.BooleanField(default=False, help_text="Does this bird cost one food to play?")
    eggs = models.PositiveIntegerField(default=0)
    cached_food = models.PositiveIntegerField(default=0)
    tucked_cards = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name
    
    def clean(self):
        if self.eggs > self.nest_size:
            self.eggs = self.nest_size
        
    class Meta:
        ordering = ['name']

    
class EndRoundGoal(models.Model):
    GOALS = {
        'NG': 'No Goal',
        'EF': 'Eggs in Forest',
        'EG': 'Eggs in Grassland',
        'EW': 'Eggs in Wetland',
        'BF': 'Birds in Forest',
        'BG': 'Birds in Grassland',
        'BW': 'Birds in Wetland',
        'BFC': 'Food Cost of Played Birds',
        'WFC': 'Worms in Food Cost',
        'CWFC': 'Cherries and Wheat in Food Cost',
        'FRFC': 'Fish and Rats in Food Cost',
        'BTC': 'Birds with Tucked Cards',
        'BRB': 'Birds with Brown Power',
        'WHB': 'Birds with White or No Power',
        'ECVTY': 'Eggs in Cavity Nests',
        'EBWL': 'Eggs in Bowl Nests',
        'ESTK': 'Eggs in Stick Nests',
        'EGRD': 'Eggs in Ground Nests',
        'CVTYBE': 'Cavity Nest Birds with Eggs',
        'BWLBE': 'Bowl Nest Birds with Eggs',
        'STKBE': 'Stick Nest Birds with Eggs',
        'GRDBE': 'Ground Nest Birds with Eggs',
        'BNE': 'Birds with No Eggs',
        'BGTF': 'Birds worth <4 points',
        'BLTF': 'Birds worth >4 points',
        'FIPS': 'Food in Personal Supply',
        'BIH': 'Bird Cards in Hand',
        'SE': 'Sets of Eggs',
        'FC': 'Filled Columns',
        'BIAR': 'Birds in one Row',
        'PLAYB': 'Number of Played Birds',
        'BPR': 'Beaks Pointing Right',
        'BPL': 'Beaks Pointing Left',
        'CPLAYB': 'Cubes on \"Play a Bird\"',
    }
    id = models.AutoField(primary_key=True)
    goal = models.CharField(max_length=50, choices=GOALS.items(), default='No Goal')
    score = models.PositiveIntegerField(default=0, blank=True)

    def __str__(self):
        return self.goal
    
    def calculate_score(self, board):
        score = 0
        if self.goal == 'No Goal':
            return 0
        elif self.goal == 'Eggs in Forest':
            for bird in board.get_forest_birds():
                score += bird.eggs
        elif self.goal == 'Eggs in Grassland':
            for bird in board.get_grassland_birds():
                score += bird.eggs
        elif self.goal == 'Eggs in Wetland':
            for bird in board.get_wetland_birds():
                score += bird.eggs
        elif self.goal == 'Birds in Forest':
            return len(board.get_forest_birds())
        elif self.goal == 'Birds in Grassland':
            return len(board.get_grassland_birds())
        elif self.goal == 'Birds in Wetland':
            return len(board.get_wetland_birds())
        elif self.goal == 'Food Cost of Played Birds':
            for bird in board.get_all_birds():
                score += len(FoodJunction.objects.filter(card=bird))
        elif self.goal == 'Worms in Food Cost':
            for bird in board.get_all_birds():
                foods = FoodJunction.objects.filter(card=bird).values_list('food__food_name', flat=True)
                for f in foods:
                    if 'Worm' in f:
                        score += 1
        elif self.goal == 'Cherries and Wheat in Food Cost':
            for bird in board.get_all_birds():

birdie-game/aviary/templates/aviary/add_bonus_card.html
<!DOCTYPE html>
{% load static %}
<head>
    <script>
        /*to prevent Firefox FOUC, this must be here*/
        let FF_FOUC_FIX;
    </script></head>
<body>
    <h1>Add Bonus Card</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">Add</button>
    </form>
</body>
<a href="{% url 'bonus_cards' board.pk %}" class="button">Back to Bonus Cards</a>

birdie-game/aviary/templates/aviary/birdcard.html
<!DOCTYPE html>
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'aviary/css/birdcard.css' %}">
  
</head>
<body>
  {% if bird is not None %}
    <div class="top-row">
      <div class="habitats">
        {% for habitat in bird.habitats.all %}
          {% if habitat.habitat_name == "Forest" %}
            <img src="{% static 'aviary/img/forest.jpg' %}" alt="forest"/>
          {% elif habitat.habitat_name == "Grassland" %}
            <img src="{% static 'aviary/img/grassland.jpg' %}" alt="grassland"/>
          {% elif habitat.habitat_name == "Wetland" %}
            <img src="{% static 'aviary/img/wetland.jpg' %}" alt="wetland"/>
          {% endif %}
        {% endfor %}
      </div>
      <div class="food">
        {% for food_group in food %}
          {% for f in food_group %}
            {% if f == "Worm" %}
              <img src="{% static 'aviary/img/worm.jpg' %}" alt="worm"/>
            {% elif f == "Wheat" %}
              <img src="{% static 'aviary/img/wheat.jpg' %}" alt="wheat"/>
            {% elif f == "Cherry" %}
              <img src="{% static 'aviary/img/cherry.jpg' %}" alt="cherry"/>
            {% elif f == "Rat" %}
              <img src="{% static 'aviary/img/rat.jpg' %}" alt="rat"/>
            {% elif f == "Fish" %}
              <img src="{% static 'aviary/img/fish.jpg' %}" alt="fish"/>
            {% elif f == "Nectar" %}
              <img src="{% static 'aviary/img/nectar.jpg' %}" alt="nectar"/>
            {% elif f == "Wild" %}
              <img src="{% static 'aviary/img/wild.jpg' %}" alt="wild"/>
            {% endif %}
            {% if not forloop.last %}
              /
            {% endif %}
          {% endfor %}
          {% if not forloop.last %}
            +
          {% endif %}
        {% endfor %}
      </div>
    </div>
    <div class="name-row">
      <p id="name">{{ bird.name }}</p>
    </div>
    <div class="image-row">
      <div>
      {% if bird.direction_facing == "l" %}
        <img id="bird_facing" src="{% static 'aviary/img/left_facing.jpg' %}" alt="{{ bird.name }}"/>
      {% elif bird.direction_facing == "r" %}
        <img id="bird_facing" src="{% static 'aviary/img/right_facing.jpg' %}" alt="{{ bird.name }}"/>
      {% elif bird.direction_facing == "f" %}
        <img id="bird_facing" src="{% static 'aviary/img/forward_facing.jpg' %}" alt="{{ bird.name }}"/>
      {% else %}
      {% endif %}
      </div>
    </div>

    <div class="middle-row">
      <div class="feathers">
        <img src="{% static 'aviary/img/feather.jpg' %}" alt="feathers"/>
        <p>{{ bird.feathers }}</p>
      </div>
      <div class="nests">
        {% if bird.nest_type == 'g' %}
          <img src="{% static 'aviary/img/ground.jpg' %}" alt="ground nest"/>
        {% elif bird.nest_type == 'a' %}
          <img src="{% static 'aviary/img/star.jpg' %}" alt="star nest"/>    
        {% elif bird.nest_type == 'b' %}
          <img src="{% static 'aviary/img/bowl.jpg' %}" alt="bowl nest"/>
        {% elif bird.nest_type == 'c' %}
          <img src="{% static 'aviary/img/cavity.jpg' %}" alt="cavity nest"/>
        {% elif bird.nest_type == 's' %}
          <img src="{% static 'aviary/img/stick.jpg' %}" alt="stick nest"/>
        {% endif %}
        {% if bird.nest_type != 'n' %}
          <p>{{ bird.eggs }}/{{ bird.nest_size }}</p>
        {% endif %}
      </div>
      <div class="wingspan">
        <h1>&#8596;</h1>
        <p>{{ bird.wingspan }}</p>
      </div>
      <div class="cached_food">
        <img src="{% static 'aviary/img/wild.jpg' %}" width="50px" height="50px" alt="wild">
        <p>{{ bird.cached_food }}</p>
      </div>
      <div class="tucked_cards">
        <img src="{% static 'aviary/img/tucked_cards.jpg' %}" alt="tucked_cards">
        <p>{{ bird.tucked_cards }}</p>
      </div>
    </div>

    <div class="ability-{{ bird.ability_type }}">
      <p>{{ bird.ability_desc }}</p>
    </div>
  {% endif %}
</body>

birdie-game/aviary/templates/aviary/birdcard_update.html
{% load static %}
<link rel="stylesheet" href="{% static 'aviary/css/birdcard_update.css' %}">

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

birdie-game/aviary/templates/aviary/bonus_cards.html
<!DOCTYPE html>
{% load static %}
{% csrf_token %}
{{ board.pk|json_script:"board"}}
<head>
    <link rel="stylesheet" href="{% static 'aviary/css/button.css' %}">
    <link rel="stylesheet" href="{% static 'aviary/css/bonus_cards.css' %}">
    <script>
        /*to prevent Firefox FOUC, this must be here*/
        let FF_FOUC_FIX;
  </script>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'board' board.pk %}" class="button" id="board">Board</a>
        <a href="" class="button header" id="edit">Bonus Cards</a>
        <a href="{% url 'end_of_round_goals' board.pk %}" class="button" id="round-goals">End of Round Goals</a>
    </div>
    <div class="body">
        {% if board.bonus_cards.all %}
            <div class="bonus-cards">
                {% for card in board.bonus_cards.all %}
                    <div class="bonus-card">
                        <label for="bonus-card-{{ card.pk }}">{{ card.bonus }}: {{ card.get_bonus_display }}</label>
                        <select id="bonus-card-{{ card.pk }}" name="bonus-card-{{ card.pk }}">
                            {% for bonus in BonusCard.BONUSES.items %}
                                <option value="{{ bonus.0 }}" {% if card.bonus == bonus.0 %}selected{% endif %}>
                                    {{ bonus.1 }}
                                </option>
                            {% endfor %}
                        </select>
                        <strong id="score-{{ card.pk }}">Score: {{ card.score }}</strong>
                        <a href="{% url 'delete_bonus_card' board.pk card.pk %}" class="button delete">Delete</a>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No bonus cards available.</p>
        {% endif %}
        <a href="{% url 'add_bonus_card' board.pk %}" id="add-bonus-card" class="button">Add Bonus Card</a>
    </div>
    <script>
        const board_id = JSON.parse(document.getElementById('board').textContent);
        document.addEventListener('DOMContentLoaded', function () {
            document.querySelectorAll('select').forEach(function (dropdown) {
                dropdown.addEventListener('change', function () {
                    const selectedValue = this.value;
                    const cardId = this.id.split('-')[2];
                    fetch("{% url 'update_bonus_card' %}", {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}',
                        },
                        body: JSON.stringify({
                            'board_pk': board_id,
                            'card_pk': cardId,
                            'bonus': selectedValue,
                            'csrfmiddlewaretoken': '{{ csrf_token }}'
                        }),
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data.status === 'success') {
                            console.log('Bonus card updated successfully');
                            // Update DOM
                            const label = document.querySelector(`label[for="${this.id}"]`);
                            label.innerHTML = `${data.bonus_title}: ${data.bonus_description}`;
                            const score = document.querySelector(`strong[id="score-${this.id.split('-')[2]}"]`);
                            score.innerHTML = `Score: ${data.score}`;
                        } else {
                            console.error('Error updating bonus card:', data.error);
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                    });
                });
            });
        });
    </script>
</body>

birdie-game/aviary/templates/aviary/detail.html
<p>You're looking at {{ birdcard }}</p>

birdie-game/aviary/templates/aviary/end_of_round_goals.html
<!DOCTYPE html>
{% load static %}
{% csrf_token %}
{{ board.pk|json_script:"board"}}
<head>
    <link rel="stylesheet" href="{% static 'aviary/css/end_of_round_goals.css' %}">
    <link rel="stylesheet" href="{% static 'aviary/css/button.css' %}">
    <script>
        /*to prevent Firefox FOUC, this must be here*/
        let FF_FOUC_FIX;
    </script>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'bonus_cards' board.pk %}" class="button" id="bonus">Bonus Cards</a>
        <a href="" class="button header" id="edit">Edit Goals</a>
        <a href="{% url 'board' board.pk %}" class="button" id="board">Board</a>
    </div>
    <div class="body">
        <div class="round">
            <label for="round-1">Round 1</label>
            <select id="round-1" name="round-1">
                {% for goal in EndRoundGoal.GOALS.items %}
                    {% if board.end_of_round_1_goal and board.end_of_round_1_goal.goal == goal.1 %}
                        <option value="{{ goal.0 }}" selected>
                    {% else %}
                        <option value="{{ goal.0 }}">
                    {% endif %}
                        {{ goal.1 }}
                    </option>
                {% endfor %}
            </select>
            {% if board.end_of_round_1_goal %}
                <h3 class="round-display" id="round-1-display">{{ board.end_of_round_1_goal.get_goal_display }}</h3>
            {% endif %}
            <h3 class="round-score" id="round-1-score">Score: {{ board.end_of_round_1_goal.score }}</h3>
        </div>
        <div class="round">
            <label for="round-2">Round 2</label>
            <select id="round-2" name="round-2">
                {% for goal in EndRoundGoal.GOALS.items %}
                    <option value="{{ goal.0 }}" {% if board.end_of_round_2_goal and board.end_of_round_2_goal.goal == goal %}selected{% endif %}>
                        {{ goal.1 }}
                    </option>
                {% endfor %}
            </select>
            {% if board.end_of_round_2_goal %}
                <h3 class="round-display" id="round-2-display">{{ board.end_of_round_2_goal.get_goal_display }}</h3>
            {% endif %}
            <h3 class="round-score" id="round-2-score">Score: {{ board.end_of_round_2_goal.score }}</h3>
        </div> 
        <div class="round">
            <label for="round-3">Round 3</label>
            <select id="round-3" name="round-3">
                {% for goal in EndRoundGoal.GOALS.items %}
                    <option value="{{ goal.0 }}" {% if board.end_of_round_3_goal and board.end_of_round_3_goal.goal == goal %}selected{% endif %}>
                        {{ goal.1 }}
                    </option>
                {% endfor %}
            </select>
            {% if board.end_of_round_3_goal %}
                <h3 class="round-display" id="round-3-display">{{ board.end_of_round_3_goal.get_goal_display }}</h3>
            {% endif %}
            <h3 class="round-score" id="round-3-score">Score: {{ board.end_of_round_3_goal.score }}</h3>
        </div>
        <div class="round">
            <label for="round-4">Round 4</label>
            <select id="round-4" name="round-4">
                {% for goal in EndRoundGoal.GOALS.items %}
                    <option value="{{ goal.0 }}" {% if board.end_of_round_4_goal and board.end_of_round_4_goal.goal == goal %}selected{% endif %}>
                        {{ goal.1 }}
                    </option>
                {% endfor %}
            </select>
            {% if board.end_of_round_4_goal %}
                <h3 class="round-display" id="round-4-display">{{ board.end_of_round_4_goal.get_goal_display }}</h3>
            {% endif %}
            <h3 class="round-score" id="round-4-score">Score: {{ board.end_of_round_4_goal.score }}</h3>
        </div>

        <script>
            const board_id = JSON.parse(document.getElementById('board').textContent);
            document.addEventListener('DOMContentLoaded', function () {
                document.querySelectorAll('select').forEach(function (dropdown) {
                    dropdown.addEventListener('change', function () {
                        const rounds = [this.name];
                        const goals = [];
                        if (this.name === "round-1") {
                            goals.push(this.value);
                        } else {
                            goals.push(null);
                        }
                        if (this.name === "round-2") {
                            goals.push(this.value);
                        } else {
                            goals.push(null);
                        }
                        if (this.name === "round-3") {
                            goals.push(this.value);
                        } else {
                            goals.push(null);
                        }
                        if (this.name === "round-4") {
                            goals.push(this.value);
                        } else {
                            goals.push(null);
                        }
                        fetch("{% url 'update_end_of_round_goals' %}", {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                "X-CSRFToken": "{{ csrf_token }}",
                            },
                            body: JSON.stringify({
                                'board_id': board_id,
                                'rounds': rounds,
                                'goals': goals,
                                'csrfmiddlewaretoken': '{{ csrf_token }}'
                            }),
                        })
                        .then(response => response.json())
                        .then(data => {
                            if (data.status === 'success') {
                                console.log('Goal updated successfully');
                                // Update DOM
                                document.getElementById('round-1-display').textContent = data.goals[0];
                                document.getElementById('round-2-display').textContent = data.goals[1];
                                document.getElementById('round-3-display').textContent = data.goals[2];
                                document.getElementById('round-4-display').textContent = data.goals[3];
                                document.getElementById('round-1-score').textContent = "Score: " + data.scores[0];
                                document.getElementById('round-2-score').textContent = "Score: " + data.scores[1];
                                document.getElementById('round-3-score').textContent = "Score: " + data.scores[2];
                                document.getElementById('round-4-score').textContent = "Score: " + data.scores[3];
                            } else {
                                console.error('Error updating goal: ', data.message);
                            }
                        })
                        .catch(error => {
                            alert("Error: " + error);
                        });
                    });
                });
            });
        </script>
    </div>
</body>

birdie-game/aviary/templates/aviary/index.html
<!DOCTYPE html>
{% load static %}



<head>
    <link rel="stylesheet" href="{% static 'aviary/css/index.css' %}">
    <script>
        /*to prevent Firefox FOUC, this must be here*/
        let FF_FOUC_FIX;
    </script>
</head>
<body>
    <h1>Bird Aviary Simulator</h1>
    <div class="options">
        <a class="new" href="{% url 'create_board' %}">New Board</a>
        <a class="edit" href="">View Existing Boards</a>
    </div>
</body>

birdie-game/aviary/templates/aviary/update_board.html
<!DOCTYPE html>
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'aviary/css/update_board.css' %}">
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
</body>